"""
generate_mcp_tools.py
=====================

Code generator for the FinancialReports remote MCP server.

What it does:
  1. Pulls the live OpenAPI schema from financialreports.eu
  2. Renders src/financial_reports_mcp.py — a FastAPI host that mounts a
     FastMCP server protected by the FastMCP AWSCognitoProvider OAuth proxy.
  3. Every tool is wrapped in a soft-gate (`@subscription_required`) that
     returns an upgrade-link markdown response for free-tier users instead
     of a hard 403, so the LLM can render the upgrade link inline.

Run:
    python scripts/generate_mcp_tools.py

This script is invoked at Docker build time (see Dockerfile).
"""

import re
import sys
import time
from pathlib import Path
from typing import Any

import httpx
import jinja2
import yaml

SCHEMA_URL = "https://financialreports.eu/api/schema/"
OUTPUT_FILE = Path(__file__).parent.parent / "src" / "financial_reports_mcp.py"


# ---------------------------------------------------------------------------
# FILE HEADER — everything above the generated tool functions
# ---------------------------------------------------------------------------
# NOTE: this is a raw Python source string written verbatim to the output file.
# Jinja is NOT applied to it. Only the tool templates below use Jinja.

FILE_HEADER_TEMPLATE = '''"""
AUTO-GENERATED by scripts/generate_mcp_tools.py — DO NOT EDIT MANUALLY.

Architecture:
  - FastAPI host serves /health, /favicon.ico, /icon.png, and a browser
    landing page.
  - FastMCP server (mounted at /mcp) is protected by AWSCognitoProvider, which
    handles the entire OAuth proxy: /authorize, /token, /register,
    /auth/callback, /.well-known/oauth-protected-resource,
    /.well-known/oauth-authorization-server, plus JWKS-based JWT validation.
  - Every tool is decorated with @subscription_required, which checks the
    authenticated user's subscription against the FinancialReports Django
    backend (with a 15s in-memory cache) and returns an upgrade-link
    markdown response for free-tier users.
"""
import asyncio
import ipaddress
import json as _json
import logging
import os
import re
import threading
import time
from contextlib import asynccontextmanager
from contextvars import ContextVar
from functools import wraps
from typing import Any, AsyncIterator, Awaitable, Callable, Optional
from urllib.parse import quote, urlsplit

import httpx
import uvicorn
from cachetools import TTLCache
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, JSONResponse, Response
from fastmcp import FastMCP
from fastmcp.server.auth.providers.aws import AWSCognitoProvider
from fastmcp.server.dependencies import get_access_token
from mcp.types import Icon, ToolAnnotations
from starlette.middleware.base import BaseHTTPMiddleware

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=os.environ.get("LOG_LEVEL", "INFO"),
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
# httpx logs every request line at INFO. At production traffic volume this
# is the dominant log line and serves no operational purpose — silence it.
logging.getLogger("httpx").setLevel(logging.WARNING)
logger = logging.getLogger("financial-reports-mcp")

# ---------------------------------------------------------------------------
# Configuration (env-driven, no hardcoded secrets)
# ---------------------------------------------------------------------------
COGNITO_USER_POOL_ID = os.environ["COGNITO_USER_POOL_ID"]
COGNITO_CLIENT_ID = os.environ["COGNITO_CLIENT_ID"]
COGNITO_CLIENT_SECRET = os.environ["COGNITO_CLIENT_SECRET"]
COGNITO_REGION = os.environ.get("COGNITO_REGION", "eu-central-1")

MCP_BASE_URL = os.environ.get("MCP_BASE_URL", "https://mcp.financialfilings.com")
API_BASE_URL = os.environ.get("API_BASE_URL", "https://api.financialreports.eu")
VERIFY_URL = os.environ.get(
    "VERIFY_URL",
    "https://api.financialreports.eu/api/mcp/verify/",
)
UPGRADE_URL = os.environ.get(
    "UPGRADE_URL",
    "https://financialreports.eu/pricing/?utm_source=mcp&utm_medium=connector",
)
LANDING_URL = os.environ.get(
    "LANDING_URL",
    "https://financialreports.eu/integrations/claude/",
)
# Public legal pages — surfaced as a footer on the connector landing
# page so users (and Anthropic reviewers) can find Privacy / Terms /
# Imprint without leaving the MCP server origin.
PRIVACY_URL = os.environ.get(
    "PRIVACY_URL", "https://financialreports.eu/data-privacy/"
)
TERMS_URL = os.environ.get(
    "TERMS_URL", "https://financialreports.eu/terms/"
)
IMPRINT_URL = os.environ.get(
    "IMPRINT_URL", "https://financialreports.eu/imprint/"
)
SUPPORT_URL = os.environ.get(
    "SUPPORT_URL", "https://financialreports.eu/contact/"
)
# Optional. When set, FastMCP's OAuth proxy stores client registrations,
# transactions, codes, and refresh tokens in Redis (shared across replicas,
# survives container restarts). When unset, FastMCP falls back to an
# encrypted DiskStore on the container's local disk — fine for dev, but on
# Azure Container Apps the disk is ephemeral, so every deploy or replica
# rotation forces every user to re-authenticate.
#
# Format: standard Redis URL, e.g.
#   rediss://:<auth-token>@<endpoint>:<port>/3?ssl_cert_reqs=required
# Use a dedicated DB number that does not collide with Celery (0) or the
# Django cache (1).
MCP_REDIS_URL = os.environ.get("MCP_REDIS_URL")

_CDN_BASE = (
    "https://cdn.financialreports.eu/financialreports/static/"
    "assets/favicon/new"
)
FAVICON_URL = f"{_CDN_BASE}/favicon.ico"
# PNG variants advertised in MCP server metadata. Connector UIs (Claude,
# ChatGPT, Cursor) reliably render PNG/SVG icons; ICO is silently dropped
# by some clients, which is why /favicon.ico alone is not enough. The MCP
# 2025-11-25 spec uses an `icons` array with `src` / `mimeType` / `sizes`
# entries; multiple sizes let renderers pick the right resolution
# (Claude.ai prefers ≥48×48; the connector directory thumbnail wants ≥256).
ICON_URL = f"{_CDN_BASE}/favicon-32x32.png"
ICON_URL_192 = f"{_CDN_BASE}/android-chrome-192x192.png"
ICON_URL_512 = f"{_CDN_BASE}/android-chrome-512x512.png"
APPLE_TOUCH_URL = f"{_CDN_BASE}/apple-touch-icon.png"

# Public-facing landing for connector users (linked from / and from MCP
# `serverInfo.websiteUrl`).
WEBSITE_URL = LANDING_URL

# Allowed `Origin` values on the /mcp Streamable HTTP endpoint. The MCP
# 2025-11-25 spec REQUIRES servers to validate Origin to prevent
# DNS-rebinding attacks (Transports §Security Warning); FastMCP doesn't
# enforce this on its own. Anything not on this list is rejected with
# HTTP 403.
#
# Notes:
#   - Requests from server-side clients (Claude.ai server, Cursor agent
#     workers, ChatGPT) typically don't send Origin, so the middleware
#     only acts when Origin is present.
#   - We accept exact hosts and any subdomain of *.anthropic.com. Add
#     entries here if a new connector host appears.
ALLOWED_MCP_ORIGINS = {
    "https://claude.ai",
    "https://claude.com",
    "https://chatgpt.com",
    "https://chat.openai.com",
    "https://www.cursor.com",
    "https://cursor.sh",
    # Local dev — strip if you ever proxy a real client through here.
    "http://localhost",
    "http://127.0.0.1",
}
ALLOWED_MCP_ORIGIN_SUFFIXES = (
    ".anthropic.com",
    ".claude.ai",
    ".claude.com",
)

# Supported MCP protocol versions. The latest spec (2025-11-25) requires
# the server to 400 on requests carrying an MCP-Protocol-Version header
# whose value isn't supported, and to echo the negotiated version on
# every response after init.
SUPPORTED_MCP_PROTOCOL_VERSIONS = frozenset(
    {
        "2024-11-05",
        "2025-03-26",
        "2025-06-18",
        "2025-11-25",
    }
)
DEFAULT_MCP_PROTOCOL_VERSION = "2025-11-25"

MCP_VERSION = os.environ.get("MCP_VERSION", "dev")

def _redact_redis_url(url: str) -> str:
    """Return host:port for a Redis URL, dropping any embedded credentials.

    str.split("@") leaks token suffix if the password literally contains "@".
    urlsplit handles RFC 3986 URLs correctly (rediss://:tok@host:6380/3 →
    "host:6380"). Falls back to "redis-store" if the URL is unparseable.
    """
    try:
        parsed = urlsplit(url)
    except ValueError:
        return "redis-store"
    host = parsed.hostname or "redis-store"
    return f"{host}:{parsed.port}" if parsed.port else host


# ---------------------------------------------------------------------------
# FastMCP server with AWS Cognito OAuth proxy
# ---------------------------------------------------------------------------
# Build OAuth state storage. Redis if MCP_REDIS_URL is set, otherwise None
# (FastMCP defaults to an encrypted DiskStore in `~/.local/share/fastmcp/`).
_oauth_storage: Any = None
if MCP_REDIS_URL:
    # Imported lazily so the redis client isn't required when running in
    # disk mode (dev, smoke tests).
    from key_value.aio.stores.redis import RedisStore

    _oauth_storage = RedisStore(
        url=MCP_REDIS_URL,
        default_collection="financial-reports-mcp-oauth",
    )
    logger.info("OAuth state -> Redis (%s)", _redact_redis_url(MCP_REDIS_URL))
else:
    logger.warning(
        "MCP_REDIS_URL not set — using FastMCP default DiskStore for OAuth "
        "state. Refresh tokens will NOT persist across container restarts "
        "or be shared across replicas; users will be forced to re-auth on "
        "every deploy."
    )

# Explicit allowlist of redirect URIs MCP clients (Claude, ChatGPT,
# Cursor, etc.) may register via Dynamic Client Registration. Passing an
# explicit list makes the policy auditable for Anthropic's connector
# review and prevents accidental regression if FastMCP's default ever
# flips back to localhost-only.
ALLOWED_CLIENT_REDIRECT_URI_PATTERNS = [
    # Anthropic — current and legacy hostnames.
    "https://claude.ai/api/mcp/auth_callback",
    "https://claude.com/api/mcp/auth_callback",
    "https://*.claude.ai/*",
    "https://*.claude.com/*",
    "https://*.anthropic.com/*",
    # OpenAI / ChatGPT MCP integrations.
    "https://chatgpt.com/*",
    "https://chat.openai.com/*",
    # Cursor.
    "https://cursor.sh/*",
    "https://www.cursor.com/*",
    "https://*.cursor.com/*",
    "cursor://*",
    # Local development (mcp-inspector, dev tools).
    "http://localhost:*",
    "http://127.0.0.1:*",
    "http://[::1]:*",
]

auth_provider = AWSCognitoProvider(
    user_pool_id=COGNITO_USER_POOL_ID,
    aws_region=COGNITO_REGION,
    client_id=COGNITO_CLIENT_ID,
    client_secret=COGNITO_CLIENT_SECRET,
    base_url=MCP_BASE_URL,
    redirect_path="/auth/callback",
    required_scopes=["openid", "email", "profile"],
    allowed_client_redirect_uris=ALLOWED_CLIENT_REDIRECT_URI_PATTERNS,
    client_storage=_oauth_storage,
)

mcp = FastMCP(
    name="FinancialReports",
    version=MCP_VERSION,
    website_url=WEBSITE_URL,
    instructions=(
        "FinancialReports gives you direct access to regulatory filings from "
        "listed companies worldwide — comparable to S&P Capital IQ or FactSet. "
        "Use these tools to search filings, retrieve full filing content as "
        "Markdown, look up companies by name or ISIN, browse industry "
        "classifications, and manage user watchlists. All data is sourced "
        "directly from official regulators."
    ),
    auth=auth_provider,
    # Multi-size icons let connector renderers pick the right resolution.
    # Claude.ai connector cards prefer the 192/512 PNG over the 32×32 favicon.
    #
    # IMPORTANT: advertise URLs from THIS server's own origin, not the CDN.
    # Three reasons:
    #   1. FastMCP's auto-generated /consent OAuth page renders this URL as
    #      the page logo. Our own CSP (img-src 'self' data:) blocks any
    #      cross-origin image, so a CDN URL silently breaks the consent
    #      page branding.
    #   2. Several MCP host UIs (incl. Claude.ai) prefer same-origin icons
    #      that match the connector's resource URI — cross-origin
    #      advertisements may silently fail to render.
    #   3. The /icon-*.png routes on this server already proxy + cache the
    #      same CDN bytes, so there's no asset cost — just URL hygiene.
    icons=[
        Icon(src=f"{MCP_BASE_URL.rstrip('/')}/icon.png", mimeType="image/png", sizes=["32x32"]),
        Icon(src=f"{MCP_BASE_URL.rstrip('/')}/icon-192.png", mimeType="image/png", sizes=["192x192"]),
        Icon(src=f"{MCP_BASE_URL.rstrip('/')}/icon-512.png", mimeType="image/png", sizes=["512x512"]),
    ],
)

# ---------------------------------------------------------------------------
# Per-request context (token + user info), set by @subscription_required
# ---------------------------------------------------------------------------
_current_token: ContextVar[str] = ContextVar("_current_token", default="")
_current_user: ContextVar[dict[str, Any]] = ContextVar("_current_user", default={})

# ---------------------------------------------------------------------------
# Subscription verification cache
# ---------------------------------------------------------------------------
# Keyed by Cognito `sub`. 15s TTL absorbs repeated calls within a single LLM
# turn while keeping downgrade/cancellation propagation tight. Note: this
# cache is per-replica on Azure Container Apps; for true cross-replica
# consistency, move to Redis. cachetools.TTLCache itself is not thread-safe,
# so all access is guarded by `_subscription_cache_lock` below.
_subscription_cache: TTLCache = TTLCache(maxsize=10000, ttl=15)
_subscription_cache_lock = threading.Lock()

# Per-`sub` in-flight verify tracking. Prevents the thundering-herd pattern
# where parallel tool calls from a single LLM session all hit the verify
# endpoint on the very first call (before the cache is populated). Only one
# verify call per sub is in flight at a time; the others wait and reuse
# the cached result. Entries are removed once the verify completes.
_subscription_inflight: dict[str, asyncio.Lock] = {}


# ---------------------------------------------------------------------------
# Shared HTTP client — module-level for connection-pool reuse
# ---------------------------------------------------------------------------
async def _inject_auth(request: httpx.Request) -> None:
    """Add Authorization from `_current_token` if not already set on the request.

    Tool wrappers run inside `subscription_required`, which sets the
    contextvar, so they don't need to pass Authorization explicitly.
    `_check_subscription` runs BEFORE the contextvar is set, so it passes
    Authorization explicitly and this hook becomes a no-op for that call.
    """
    if "Authorization" not in request.headers:
        token = _current_token.get()
        if token:
            request.headers["Authorization"] = f"Bearer {token}"


# A single AsyncClient per process. Connection pool + HTTP keep-alive are
# reused across all tool calls. Closed on shutdown via the FastAPI lifespan
# below. Limits are explicit to bound burst load against the upstream API
# (a single Claude session routinely fans out 5–10 parallel tool calls;
# at 10 replicas the unbounded default lets us spike hundreds of TLS
# handshakes against api.financialreports.eu). HTTP/2 multiplexes those
# parallel calls over a single connection.
_api_client = httpx.AsyncClient(
    base_url=API_BASE_URL,
    timeout=60.0,
    limits=httpx.Limits(
        max_connections=100,
        max_keepalive_connections=20,
        keepalive_expiry=30.0,
    ),
    http2=True,
    event_hooks={"request": [_inject_auth]},
    headers={
        # Must start with "FinancialReports-MCP-Server" — the Django admin
        # dashboard filters APIRequestLog by this exact prefix.
        "User-Agent": f"FinancialReports-MCP-Server/{MCP_VERSION}",
    },
)


async def _check_subscription(token: str, sub: str) -> dict[str, Any]:
    """Check whether the current user has an active paid subscription.

    Cached per-`sub` for the TTL of `_subscription_cache`. Definitive backend
    responses (HTTP 200/401/403) are cached; transient failures (network
    errors, timeouts, unexpected status codes) are NOT cached, so a brief
    Django blip does not lock paid users out for the full TTL.

    Stampede-protected: only one in-flight verify per `sub` at a time; the
    others wait and reuse the cached result.

    Cancel-safe: the `_subscription_inflight[sub]` entry is always popped
    in `finally`, so a CancelledError (which inherits from BaseException
    and bypasses `except Exception`) cannot leave a permanently-held lock
    that would deadlock subsequent calls from the same user.
    """
    with _subscription_cache_lock:
        cached = _subscription_cache.get(sub)
    if cached is not None:
        return cached

    # `dict.setdefault` is atomic under the GIL, so this is safe across
    # concurrent coroutines without a separate guard.
    lock = _subscription_inflight.setdefault(sub, asyncio.Lock())
    try:
        async with lock:
            # Re-check the cache after acquiring the lock — another coroutine
            # may have populated it while we were waiting.
            with _subscription_cache_lock:
                cached = _subscription_cache.get(sub)
            if cached is not None:
                return cached

            cacheable = False
            try:
                resp = await _api_client.get(
                    VERIFY_URL,
                    headers={"Authorization": f"Bearer {token}"},
                    timeout=10.0,
                )
                if resp.status_code == 200:
                    payload = {}
                    try:
                        payload = resp.json()
                    except ValueError:
                        logger.debug("verify 200 had non-JSON body sub=%s", sub[:8])
                    result = {
                        "authorized": True,
                        "plan": payload.get("plan"),
                        "user_id": payload.get("user_id"),
                    }
                    logger.info("verify ok sub=%s plan=%s", sub[:8], result.get("plan"))
                    cacheable = True
                elif resp.status_code in (401, 403):
                    payload = {}
                    try:
                        payload = resp.json()
                    except ValueError:
                        logger.debug(
                            "verify %s had non-JSON body sub=%s", resp.status_code, sub[:8]
                        )
                    result = {
                        "authorized": False,
                        "reason": payload.get("reason", "subscription_required"),
                        "upgrade_url": payload.get("upgrade_url", UPGRADE_URL),
                    }
                    logger.info(
                        "verify denied sub=%s status=%s reason=%s",
                        sub[:8],
                        resp.status_code,
                        result.get("reason"),
                    )
                    cacheable = True
                else:
                    logger.warning(
                        "verify unexpected status=%s body=%s",
                        resp.status_code,
                        resp.text[:200],
                    )
                    result = {
                        "authorized": False,
                        "reason": "verification_failed",
                        "upgrade_url": UPGRADE_URL,
                    }
                    # Do not cache: treat unexpected statuses as transient.
            except Exception as exc:
                logger.exception("verify call failed: %s", exc)
                result = {
                    "authorized": False,
                    "reason": "verification_error",
                    "upgrade_url": UPGRADE_URL,
                }
                # Do not cache: next call should retry.

            if cacheable:
                with _subscription_cache_lock:
                    _subscription_cache[sub] = result
            return result
    finally:
        _subscription_inflight.pop(sub, None)


def _upgrade_response(upgrade_url: str) -> str:
    """Markdown payload returned to free-tier or unauthenticated users.

    The LLM will render the link inline so the end user can click directly
    through to the pricing page from the chat.
    """
    return (
        "⚠️ **Active FinancialReports subscription required**\\n\\n"
        "This tool needs an active **Analyst** or **Enterprise** plan.\\n\\n"
        f"👉 **[Upgrade your account here →]({upgrade_url})**\\n\\n"
        "Once your subscription is active, retry this tool — access is granted "
        "immediately, no reconnection required."
    )


def subscription_required(
    func: Callable[..., Awaitable[str]],
) -> Callable[..., Awaitable[str]]:
    """Soft-gate decorator: free users get an upgrade-link markdown response.

    Reads the validated JWT via FastMCP's `get_access_token()`, looks up the
    user's subscription (cached), and either passes through to the wrapped
    function or short-circuits with the upgrade prompt. The wrapped function
    can read the raw token and user info from the contextvars at the top
    of this module.
    """

    @wraps(func)
    async def wrapper(*args: Any, **kwargs: Any) -> str:
        try:
            access_token = get_access_token()
        except Exception as exc:
            logger.warning("get_access_token raised: %s", exc)
            return _upgrade_response(UPGRADE_URL)

        if access_token is None:
            return _upgrade_response(UPGRADE_URL)

        claims = getattr(access_token, "claims", {}) or {}
        sub = claims.get("sub")
        raw_token = getattr(access_token, "token", None)

        if not sub or not raw_token:
            logger.warning("missing sub or token on access_token")
            return _upgrade_response(UPGRADE_URL)

        # Defense in depth against cross-app-client token replay.
        #
        # MCP 2025-11-25 §Authorization mandates: "MCP servers MUST validate
        # that access tokens were issued specifically for them as the
        # intended audience". For Cognito access tokens this means checking
        # both:
        #   - `client_id` claim matches our Cognito app (so a token minted
        #     for a *different* app client in the same user pool can't be
        #     replayed against this server), AND
        #   - `aud` claim, when present, is either our `client_id` (Cognito's
        #     default audience) or our canonical resource URI (the form
        #     reviewers expect per RFC 8707, future-proofing for when we
        #     migrate to a Cognito Resource Server identifier).
        #
        # FastMCP's AWSCognitoProvider doesn't enforce either binding, so we
        # fail closed here.
        token_client_id = claims.get("client_id") or getattr(
            access_token, "client_id", None
        )
        if token_client_id != COGNITO_CLIENT_ID:
            logger.warning(
                "rejecting token: client_id=%r expected=%r sub=%s",
                token_client_id,
                COGNITO_CLIENT_ID,
                sub[:8],
            )
            return _upgrade_response(UPGRADE_URL)

        canonical_resource = f"{MCP_BASE_URL.rstrip('/')}/mcp"
        accepted_audiences = {COGNITO_CLIENT_ID, canonical_resource, MCP_BASE_URL.rstrip("/")}
        aud_claim = claims.get("aud")
        if aud_claim is not None:
            aud_values = aud_claim if isinstance(aud_claim, list) else [aud_claim]
            if not any(a in accepted_audiences for a in aud_values):
                logger.warning(
                    "rejecting token: aud=%r not in %r sub=%s",
                    aud_claim,
                    accepted_audiences,
                    sub[:8],
                )
                return _upgrade_response(UPGRADE_URL)

        check = await _check_subscription(raw_token, sub)
        if not check.get("authorized"):
            return _upgrade_response(check.get("upgrade_url") or UPGRADE_URL)

        token_reset = _current_token.set(raw_token)
        user_reset = _current_user.set(check)
        try:
            return await func(*args, **kwargs)
        finally:
            _current_token.reset(token_reset)
            _current_user.reset(user_reset)

    return wrapper


# ---------------------------------------------------------------------------
# Backend client check — invoked at the top of every tool wrapper to fail
# fast (with a generic message) if the wrapper is somehow called without
# the contextvar being set. Real I/O is done via the module-level
# `_api_client`; auth is injected automatically by `_inject_auth`.
# ---------------------------------------------------------------------------
def _require_auth_context() -> None:
    if not _current_token.get():
        logger.error("tool wrapper called without a token in context")
        raise RuntimeError("Authentication required.")


class SubscriptionGateError(RuntimeError):
    """Raised by structured tools when the caller lacks an active subscription.

    Structured tools (`output_schema=` declared) can't return the markdown
    upgrade-link soft-gate response that unstructured tools use, because
    the markdown string would not conform to the declared schema and
    FastMCP would emit a server error. Instead they raise this; FastMCP
    surfaces it as a tool error (`isError: true`) with this exception's
    message as the tool's text content. The LLM sees the upgrade prompt
    in the same form it would have seen it as a soft-gate.
    """


async def _authorize_or_raise() -> tuple[Any, Any]:
    """Token-validate + subscription-check for structured tools.

    Same checks `subscription_required` runs, but raises
    `SubscriptionGateError` instead of returning markdown when the
    caller is unauthorized. Returns the (token_reset, user_reset)
    pair the tool body must reset in `finally`.
    """
    try:
        access_token = get_access_token()
    except Exception as exc:
        logger.warning("get_access_token raised: %s", exc)
        raise SubscriptionGateError(_upgrade_response(UPGRADE_URL)) from exc

    if access_token is None:
        raise SubscriptionGateError(_upgrade_response(UPGRADE_URL))

    claims = getattr(access_token, "claims", {}) or {}
    sub = claims.get("sub")
    raw_token = getattr(access_token, "token", None)

    if not sub or not raw_token:
        raise SubscriptionGateError(_upgrade_response(UPGRADE_URL))

    token_client_id = claims.get("client_id") or getattr(
        access_token, "client_id", None
    )
    if token_client_id != COGNITO_CLIENT_ID:
        logger.warning(
            "rejecting token: client_id=%r expected=%r sub=%s",
            token_client_id,
            COGNITO_CLIENT_ID,
            sub[:8],
        )
        raise SubscriptionGateError(_upgrade_response(UPGRADE_URL))

    canonical_resource = f"{MCP_BASE_URL.rstrip('/')}/mcp"
    accepted_audiences = {COGNITO_CLIENT_ID, canonical_resource, MCP_BASE_URL.rstrip("/")}
    aud_claim = claims.get("aud")
    if aud_claim is not None:
        aud_values = aud_claim if isinstance(aud_claim, list) else [aud_claim]
        if not any(a in accepted_audiences for a in aud_values):
            logger.warning(
                "rejecting token: aud=%r not in %r sub=%s",
                aud_claim,
                accepted_audiences,
                sub[:8],
            )
            raise SubscriptionGateError(_upgrade_response(UPGRADE_URL))

    check = await _check_subscription(raw_token, sub)
    if not check.get("authorized"):
        raise SubscriptionGateError(
            _upgrade_response(check.get("upgrade_url") or UPGRADE_URL)
        )

    token_reset = _current_token.set(raw_token)
    user_reset = _current_user.set(check)
    return token_reset, user_reset


def _release_auth_context(resets: tuple[Any, Any]) -> None:
    token_reset, user_reset = resets
    _current_token.reset(token_reset)
    _current_user.reset(user_reset)


def _format_response(response: httpx.Response) -> str:
    """Format an httpx.Response as a JSON code block for the LLM.

    Sync — no I/O happens here, the response body is already buffered by httpx.
    """
    try:
        response.raise_for_status()
        data = response.json()
        return f"```json\\n{_json.dumps(data, indent=2, ensure_ascii=False)}\\n```"
    except httpx.HTTPStatusError as exc:
        return (
            f"Error {exc.response.status_code} {exc.response.reason_phrase}: "
            f"{exc.response.text[:500]}"
        )
    except Exception as exc:
        return f"Error formatting response: {exc}"


# ---------------------------------------------------------------------------
# Tool-input validation
# ---------------------------------------------------------------------------
class ToolInputError(ValueError):
    """Raised when a tool argument fails server-side validation.

    Caught at tool boundaries and turned into a user-visible error string
    rather than letting the request reach the upstream API with an unsafe
    or malformed value.
    """


# Regulator-compliant ISIN: 2 country letters + 9 alphanumerics + 1 check digit.
_ISIN_RE = re.compile(r"^[A-Z]{2}[A-Z0-9]{9}[0-9]$")
# Loose UUID match (any case, dash-separated). The FR backend accepts the
# canonical form; we just want to refuse path traversal payloads here.
_UUID_RE = re.compile(
    r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
)
# Generic safety net for any string-typed path param the generator emits.
# 128-char cap and a printable-ASCII allowlist that excludes "/", ".." path
# components, query/fragment chars, and whitespace. Tools that need richer
# inputs (e.g. UUIDs, ISINs) should be name-routed through the stricter
# validators above.
_GENERIC_PATH_RE = re.compile(r"^[A-Za-z0-9_.~:@!*'()+,;=$&%-]{1,128}$")


def _validate_path_param(name: str, value: Any) -> str:
    """Coerce + validate a path-param value before URL interpolation.

    The generated tool wrappers build URLs as `template.format(**path_params)`.
    Without validation, a string-typed parameter such as `code="../admin"`
    silently rewrites the request path with the user's bearer attached.

    Pattern-routed by the *parameter name* the OpenAPI schema declared:
      - `*_uuid`           → must be a canonical UUID
      - `code`, `*_code`   → must be a valid ISIN
      - everything else    → must match the generic-path allowlist

    Integers go through unchanged (path-traversal is impossible).
    Returns the URL-quoted string ready to slot into the path.
    """
    if isinstance(value, bool):
        raise ToolInputError(f"path parameter {name!r} must not be boolean")
    if isinstance(value, int):
        return str(value)

    s = str(value)
    if not s:
        raise ToolInputError(f"path parameter {name!r} is empty")

    if name == "code" or name.endswith("_code"):
        if not _ISIN_RE.fullmatch(s):
            raise ToolInputError(
                f"{name!r} must be a 12-character ISIN (e.g. 'US0378331005')"
            )
    elif name.endswith("_uuid") or name == "uuid":
        if not _UUID_RE.fullmatch(s):
            raise ToolInputError(
                f"{name!r} must be a UUID (e.g. '11111111-2222-3333-4444-555555555555')"
            )
    else:
        if not _GENERIC_PATH_RE.fullmatch(s):
            raise ToolInputError(
                f"{name!r} contains characters that are not allowed in a URL path segment"
            )

    # quote() with safe="" turns any residual "/" or "?" into %2F / %3F so
    # path traversal is structurally impossible even if the regex above
    # ever expanded.
    return quote(s, safe="")


def _validate_webhook_url(value: Any) -> str:
    """Block obvious SSRF amplification targets at the MCP boundary.

    The Django backend is responsible for the authoritative check; this is
    defense in depth so a misconfigured backend cannot be used by a
    subscriber to probe internal Azure metadata, link-local addresses,
    or loopback.
    """
    if not isinstance(value, str) or not value:
        raise ToolInputError("webhook url must be a non-empty string")
    parsed = urlsplit(value)
    if parsed.scheme != "https":
        raise ToolInputError("webhook url must use https://")
    host = parsed.hostname
    if not host:
        raise ToolInputError("webhook url is missing a host")

    # Block hostname-form private/reserved addresses. We only resolve when
    # the hostname is already an IP literal; deferring DNS to the backend
    # avoids a TOCTOU dance and matches its enforcement model.
    try:
        ip = ipaddress.ip_address(host)
    except ValueError:
        ip = None
    if ip is not None and (
        ip.is_private
        or ip.is_loopback
        or ip.is_link_local
        or ip.is_multicast
        or ip.is_reserved
        or ip.is_unspecified
    ):
        raise ToolInputError("webhook url must not target a private or loopback address")
    return value


def _safe_error(func_name: str, exc: BaseException) -> str:
    """Generic error string returned to the LLM.

    We intentionally do NOT echo the exception message — it can include
    upstream URLs, internal hostnames, or token fragments. The full
    traceback is logged server-side by the caller via logger.exception().
    """
    if isinstance(exc, ToolInputError):
        return f"Invalid argument: {exc}"
    return f"Error calling {func_name}. See server logs for details."


# ---------------------------------------------------------------------------
# FastAPI host
# ---------------------------------------------------------------------------
# FastMCP returns a Starlette app that already serves /mcp + all OAuth
# endpoints. We mount it at root, with a few FastAPI routes (health, favicon,
# browser landing) declared first so they win the route match.
mcp_app = mcp.http_app(path="/mcp")


# Cache static asset bytes in-process so connector probes (Claude, Cursor,
# ChatGPT) don't trigger one outbound CDN call per probe per replica.
# Each entry is (bytes, fetched_at). TTL 24h matches the public Cache-Control.
_ASSET_TTL = 86400.0
_asset_cache: dict[str, tuple[bytes, str, float]] = {}
_asset_cache_lock = asyncio.Lock()


async def _fetch_asset(url: str, fallback_media: str) -> Optional[tuple[bytes, str]]:
    """Return (bytes, media_type) for a CDN-hosted static asset.

    Uses an in-process cache with `_ASSET_TTL` freshness; falls back to a
    stale entry on transient CDN failure rather than 5xxing the probe.
    Returns None if there's no cached entry and the upstream fetch fails.
    """
    now = time.monotonic()
    cached = _asset_cache.get(url)
    if cached is not None:
        data, media, fetched_at = cached
        if now - fetched_at < _ASSET_TTL:
            return data, media

    async with _asset_cache_lock:
        # Re-check after lock acquisition.
        cached = _asset_cache.get(url)
        if cached is not None:
            data, media, fetched_at = cached
            if time.monotonic() - fetched_at < _ASSET_TTL:
                return data, media
        try:
            resp = await _api_client.get(url, timeout=5.0)
            resp.raise_for_status()
            media = resp.headers.get("content-type", fallback_media)
            data = resp.content
            _asset_cache[url] = (data, media, time.monotonic())
            return data, media
        except Exception as exc:
            logger.warning("asset fetch failed url=%s err=%s", url, exc)
            if cached is not None:
                # Serve stale on failure rather than giving the probe a 204.
                return cached[0], cached[1]
            return None


@asynccontextmanager
async def _lifespan(app: FastAPI) -> AsyncIterator[None]:
    """Compose our shutdown work with FastMCP's existing lifespan.

    Also performs an explicit Redis ping when MCP_REDIS_URL is configured,
    so a misconfigured Redis URL fails the revision at boot rather than
    silently falling back to broken OAuth at first user login.
    """
    if _oauth_storage is not None and MCP_REDIS_URL:
        try:
            import redis.asyncio as _aioredis  # late import; only needed when configured

            _ping_client = _aioredis.from_url(MCP_REDIS_URL)
            try:
                await _ping_client.ping()
                logger.info("Redis ping ok (%s)", _redact_redis_url(MCP_REDIS_URL))
            finally:
                await _ping_client.aclose()
        except Exception:
            logger.exception("Redis ping failed — failing fast at startup")
            raise

    try:
        async with mcp_app.lifespan(app):
            yield
    finally:
        await _api_client.aclose()
        close = getattr(_oauth_storage, "aclose", None)
        if callable(close):
            try:
                await close()
            except Exception:
                logger.warning("oauth storage aclose() raised", exc_info=True)


app = FastAPI(
    title="FinancialReports MCP Connector",
    version=MCP_VERSION,
    lifespan=_lifespan,
    docs_url=None,
    redoc_url=None,
    openapi_url=None,
)


def _origin_allowed(origin: str) -> bool:
    if origin in ALLOWED_MCP_ORIGINS:
        return True
    try:
        host = urlsplit(origin).hostname or ""
    except ValueError:
        return False
    return any(host.endswith(suffix) for suffix in ALLOWED_MCP_ORIGIN_SUFFIXES)


class _OriginAndProtocolMiddleware(BaseHTTPMiddleware):
    """Two MCP-spec MUST checks the host server is responsible for.

    1. **Origin validation** (Transports §Security Warning, 2025-11-25):
       reject browser-origin requests carrying a foreign Origin to
       prevent DNS-rebinding attacks. We only enforce when the header
       is present, since legitimate server-to-server clients
       (Claude.ai backend, Cursor agents, ChatGPT) typically don't send
       one.

    2. **MCP-Protocol-Version handshake** (Transports §Protocol Version
       Header, 2025-11-25): if the client sent an `MCP-Protocol-Version`
       header that we don't support, return HTTP 400. Echo the negotiated
       version on every response so clients can detect downgrades.

    Both checks are scoped to the /mcp path; static endpoints (/, /health,
    /favicon.ico, /icon.png, /.well-known/*) are unaffected.
    """

    _PROTECTED_PREFIX = "/mcp"

    async def dispatch(self, request: Request, call_next: Callable[..., Any]) -> Response:
        path = request.url.path
        if path == self._PROTECTED_PREFIX or path.startswith(self._PROTECTED_PREFIX + "/"):
            origin = request.headers.get("origin")
            if origin and not _origin_allowed(origin):
                logger.warning("rejecting /mcp request: foreign origin=%r", origin)
                return JSONResponse(
                    {"error": "forbidden_origin", "error_description": f"Origin {origin!r} not allowed"},
                    status_code=403,
                )

            requested_version = request.headers.get("mcp-protocol-version")
            if (
                requested_version
                and requested_version not in SUPPORTED_MCP_PROTOCOL_VERSIONS
            ):
                logger.warning(
                    "rejecting /mcp request: unsupported MCP-Protocol-Version=%r",
                    requested_version,
                )
                return JSONResponse(
                    {
                        "error": "unsupported_protocol_version",
                        "error_description": (
                            f"MCP-Protocol-Version {requested_version!r} is not supported. "
                            f"Server supports: {sorted(SUPPORTED_MCP_PROTOCOL_VERSIONS)}."
                        ),
                        "supported_versions": sorted(SUPPORTED_MCP_PROTOCOL_VERSIONS),
                    },
                    status_code=400,
                )

        response: Response = await call_next(request)

        # Echo the negotiated protocol version so clients can detect
        # downgrades. Per spec, after init the value must be "the version
        # negotiated during initialization"; outside an init we echo the
        # server default. FastMCP doesn't surface the per-session value to
        # middleware, so this is best-effort.
        if path == self._PROTECTED_PREFIX or path.startswith(self._PROTECTED_PREFIX + "/"):
            negotiated = request.headers.get("mcp-protocol-version") or DEFAULT_MCP_PROTOCOL_VERSION
            response.headers.setdefault("MCP-Protocol-Version", negotiated)

        # Augment FastMCP's WWW-Authenticate header with the `scope=`
        # parameter the spec SHOULDs (Authorization §Protected Resource
        # Metadata Discovery). The advertised scopes MUST match what the
        # authorization server actually accepts on /register and /token,
        # because RFC-7662-aware clients (Claude) take this as the value
        # to send on dynamic client registration. We previously
        # advertised "mcp:read" — Cognito has no such scope, so DCR
        # rejected every Claude registration with `invalid_client_metadata`
        # and the user-visible result was "Couldn't reach the MCP server".
        # Use the same scopes the AS metadata advertises.
        if response.status_code in (401, 403):
            existing = response.headers.get("www-authenticate", "")
            if existing.lower().startswith("bearer") and "scope=" not in existing.lower():
                response.headers["WWW-Authenticate"] = (
                    existing + ', scope="openid email profile"'
                )

        return response


class _SecurityHeadersMiddleware(BaseHTTPMiddleware):
    """Apply baseline security headers to every response.

    The CSP is intentionally tight enough to neutralize accidental injection
    in the landing page (which contains an inline script) but permissive
    enough to allow the same-origin /favicon.ico image and the inline
    style/script blocks the landing template ships with.
    """

    _CSP = (
        "default-src 'none'; "
        "img-src 'self' data:; "
        "style-src 'self' 'unsafe-inline'; "
        "script-src 'self' 'unsafe-inline'; "
        "connect-src 'self'; "
        "base-uri 'none'; "
        "frame-ancestors 'none'"
    )

    async def dispatch(self, request: Request, call_next: Callable[..., Any]) -> Response:
        response: Response = await call_next(request)
        response.headers.setdefault("X-Content-Type-Options", "nosniff")
        response.headers.setdefault("X-Frame-Options", "DENY")
        response.headers.setdefault("Referrer-Policy", "strict-origin-when-cross-origin")
        response.headers.setdefault(
            "Permissions-Policy", "camera=(), microphone=(), geolocation=()"
        )
        # Only attach CSP to HTML responses. Applying to JSON/binary endpoints
        # is harmless but adds bytes to every probe; the landing page is the
        # only thing rendering markup we control.
        ct = response.headers.get("content-type", "")
        if ct.startswith("text/html"):
            response.headers.setdefault("Content-Security-Policy", self._CSP)
        return response


class _RegisterErrorLogger(BaseHTTPMiddleware):
    """Log /register 400s with the exact request body and our error
    response. Kept lightweight (only fires on 400, not on success) so
    it's not chatty in steady state.

    Why permanent: this is the second time we've shipped a regression
    that broke DCR (first was the Redis backend; second was the
    "scope=mcp:read" mismatch). Without seeing the request body, both
    bugs took multiple deploy cycles to diagnose. The cost of one log
    line per failed registration is far less than one user complaint.
    """

    async def dispatch(self, request: Request, call_next: Callable[..., Any]) -> Response:
        if request.url.path != "/register" or request.method != "POST":
            return await call_next(request)

        body_bytes = await request.body()

        async def replay_receive():
            return {"type": "http.request", "body": body_bytes, "more_body": False}

        request._receive = replay_receive  # type: ignore[attr-defined]

        response = await call_next(request)

        if response.status_code == 400:
            try:
                req_text = body_bytes.decode("utf-8", errors="replace")[:2000]
            except Exception:
                req_text = "<unreadable>"

            resp_chunks: list[bytes] = []
            async for chunk in response.body_iterator:  # type: ignore[attr-defined]
                resp_chunks.append(chunk)
            resp_text = b"".join(resp_chunks).decode("utf-8", errors="replace")[:1000]

            logger.warning(
                "register_400 ua=%r body=%s resp=%s",
                request.headers.get("user-agent", "?"),
                req_text,
                resp_text,
            )

            return Response(
                content=b"".join(resp_chunks),
                status_code=400,
                headers=dict(response.headers),
                media_type=response.media_type,
            )

        return response


app.add_middleware(_RegisterErrorLogger)
app.add_middleware(_OriginAndProtocolMiddleware)
app.add_middleware(_SecurityHeadersMiddleware)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    # `allow_credentials=True` combined with `allow_origins=["*"]` is rejected
    # by browsers per the Fetch spec. MCP Streamable HTTP uses a Bearer token
    # in the Authorization header, not cookies, so credentials are unnecessary.
    allow_credentials=False,
    allow_methods=["GET", "POST", "OPTIONS", "DELETE"],
    # Tightened from "*" — only the headers MCP clients actually send. Avoids
    # exposing arbitrary cross-origin probing of /health and /favicon.ico
    # while keeping every working MCP client functional.
    allow_headers=[
        "Authorization",
        "Content-Type",
        "Accept",
        "mcp-session-id",
        "mcp-protocol-version",
    ],
    # Canonical case per MCP spec, plus lowercase aliases for any client
    # whose CORS impl is case-sensitive on expose-headers.
    expose_headers=[
        "MCP-Session-Id",
        "MCP-Protocol-Version",
        "mcp-session-id",
        "mcp-protocol-version",
    ],
)


@app.get("/health")
async def health() -> dict[str, str]:
    return {
        "status": "ok",
        "service": "financial-reports-mcp",
        "version": MCP_VERSION,
    }


@app.get("/favicon.ico")
async def favicon() -> Response:
    """Serve the FR favicon. CDN-backed, in-process cached, public 24h."""
    asset = await _fetch_asset(FAVICON_URL, "image/x-icon")
    if asset is None:
        return Response(status_code=204)
    data, media = asset
    return Response(
        content=data,
        media_type=media,
        headers={"Cache-Control": "public, max-age=86400"},
    )


async def _serve_asset(url: str, fallback_media: str = "image/png") -> Response:
    asset = await _fetch_asset(url, fallback_media)
    if asset is None:
        return Response(status_code=204)
    data, media = asset
    return Response(
        content=data,
        media_type=media,
        headers={"Cache-Control": "public, max-age=86400"},
    )


@app.get("/icon.png")
async def icon_png() -> Response:
    """Default PNG icon. Some MCP connector UIs (incl. Claude) ignore the
    Icon advertised in the MCP `initialize` response and instead fetch a
    server-relative `/icon.png`. We proxy it from the same CDN asset
    `ICON_URL` advertises so both paths show the same artwork."""
    return await _serve_asset(ICON_URL)


@app.get("/icon-32.png")
async def icon_png_32() -> Response:
    return await _serve_asset(ICON_URL)


@app.get("/icon-192.png")
async def icon_png_192() -> Response:
    """Larger variant for connector renderers that prefer ≥48×48."""
    return await _serve_asset(ICON_URL_192)


@app.get("/icon-512.png")
async def icon_png_512() -> Response:
    """Connector-directory thumbnail size (Claude.ai card)."""
    return await _serve_asset(ICON_URL_512)


@app.get("/apple-touch-icon.png")
async def apple_touch_icon() -> Response:
    """iOS/touch fallback that some clients probe before /icon.png."""
    return await _serve_asset(APPLE_TOUCH_URL)


@app.get("/.well-known/oauth-protected-resource")
async def oauth_protected_resource_root() -> JSONResponse:
    """RFC 9728 fallback for clients that probe the bare path.

    FastMCP serves the path-scoped `/.well-known/oauth-protected-resource/mcp`,
    but a non-trivial number of MCP clients still hit the unsuffixed path.
    Returning the same metadata at both keeps OAuth discovery from 404ing
    on those clients without requiring a code change in FastMCP.
    """
    return JSONResponse(
        {
            "resource": f"{MCP_BASE_URL.rstrip('/')}/mcp",
            "authorization_servers": [MCP_BASE_URL.rstrip("/") + "/"],
            "scopes_supported": ["openid", "email", "profile"],
            "bearer_methods_supported": ["header"],
        }
    )


_LANDING_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FinancialReports MCP Server</title>
    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
            color: #e2e8f0;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 24px;
            line-height: 1.6;
        }
        .card {
            background: #1e293b;
            border: 1px solid #334155;
            border-radius: 16px;
            padding: 48px 40px;
            max-width: 640px;
            width: 100%;
            box-shadow: 0 20px 60px rgba(0,0,0,0.4);
        }
        h1 {
            font-size: 28px;
            font-weight: 700;
            margin-bottom: 8px;
            color: #f1f5f9;
            display: flex;
            align-items: center;
            gap: 12px;
        }
        h1 img { width: 36px; height: 36px; }
        .subtitle {
            color: #94a3b8;
            font-size: 16px;
            margin-bottom: 32px;
        }
        .alert {
            background: #422006;
            border: 1px solid #92400e;
            border-radius: 8px;
            padding: 16px 20px;
            margin-bottom: 24px;
            color: #fde68a;
            font-size: 14px;
        }
        .alert strong { color: #fbbf24; }
        .url-block {
            background: #0f172a;
            border: 2px solid #334155;
            border-radius: 10px;
            padding: 20px;
            margin: 24px 0;
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 12px;
        }
        .url-block code {
            font-family: "SF Mono", Menlo, Monaco, "Courier New", monospace;
            font-size: 15px;
            color: #38bdf8;
            font-weight: 600;
            word-break: break-all;
            user-select: all;
        }
        .copy-btn {
            background: #38bdf8;
            color: #0f172a;
            border: none;
            border-radius: 6px;
            padding: 8px 16px;
            font-size: 14px;
            font-weight: 600;
            cursor: pointer;
            white-space: nowrap;
            transition: all 0.15s;
        }
        .copy-btn:hover { background: #7dd3fc; }
        .copy-btn.copied { background: #10b981; color: white; }
        h2 {
            font-size: 18px;
            color: #f1f5f9;
            margin: 32px 0 12px;
            font-weight: 600;
        }
        ol { margin-left: 20px; color: #cbd5e1; font-size: 15px; }
        ol li { margin-bottom: 8px; }
        .footer {
            margin-top: 32px;
            padding-top: 24px;
            border-top: 1px solid #334155;
            color: #64748b;
            font-size: 13px;
            text-align: center;
        }
        .footer a { color: #38bdf8; text-decoration: none; }
        .footer a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <div class="card">
        <h1>
            <img src="/favicon.ico" alt="">
            FinancialReports MCP
        </h1>
        <p class="subtitle">
            Global regulatory filings for AI assistants. You've reached the MCP server endpoint.
        </p>

        <div class="alert">
            <strong>⚠ This URL is incomplete.</strong> To connect your AI assistant, use the full URL with <code>/mcp</code>:
        </div>

        <div class="url-block">
            <code id="mcp-url">https://mcp.financialfilings.com/mcp</code>
            <button class="copy-btn" onclick="copyUrl()" id="copy-btn">Copy</button>
        </div>

        <h2>Setup</h2>
        <ol>
            <li>Open your AI assistant's connector / integration settings (Claude, ChatGPT, Cursor, etc.)</li>
            <li>Add a new MCP server with the URL above</li>
            <li>Sign in with your FinancialReports account when prompted</li>
            <li>Start asking about company filings, financials, and disclosures</li>
        </ol>

        <div class="footer">
            <div>
                Need an account? <a href="https://financialreports.eu/pricing/?utm_source=mcp_landing">View plans</a>
                &nbsp;·&nbsp;
                <a href="__LANDING_URL__">Documentation</a>
                &nbsp;·&nbsp;
                <a href="__SUPPORT_URL__">Support</a>
            </div>
            <div style="margin-top: 12px; font-size: 12px;">
                <a href="__PRIVACY_URL__">Privacy</a>
                &nbsp;·&nbsp;
                <a href="__TERMS_URL__">Terms</a>
                &nbsp;·&nbsp;
                <a href="__IMPRINT_URL__">Imprint</a>
            </div>
        </div>
    </div>

    <script>
        function copyUrl() {
            const url = document.getElementById("mcp-url").textContent;
            const btn = document.getElementById("copy-btn");
            navigator.clipboard.writeText(url).then(() => {
                btn.textContent = "Copied!";
                btn.classList.add("copied");
                setTimeout(() => {
                    btn.textContent = "Copy";
                    btn.classList.remove("copied");
                }, 2000);
            });
        }
    </script>
</body>
</html>"""


# Pre-rendered once at module load — the URL placeholders are fixed for
# the lifetime of the process and string.replace per request was wasted
# work.
_RENDERED_LANDING_HTML = (
    _LANDING_HTML
    .replace("__LANDING_URL__", LANDING_URL)
    .replace("__PRIVACY_URL__", PRIVACY_URL)
    .replace("__TERMS_URL__", TERMS_URL)
    .replace("__IMPRINT_URL__", IMPRINT_URL)
    .replace("__SUPPORT_URL__", SUPPORT_URL)
)


@app.get("/", response_class=HTMLResponse)
async def root_landing() -> HTMLResponse:
    """Self-contained landing page for users who hit the bare domain.

    Includes a copy-button for the canonical /mcp URL and step-by-step setup
    instructions. We do NOT redirect or smart-route here — earlier experiments
    with 307-redirects from / to /mcp broke OAuth because Claude/ChatGPT/Cursor
    derive the RFC 8707 resource indicator from the URL the user typed in the
    connector dialog, causing an invalid_target mismatch downstream.
    """
    return HTMLResponse(content=_RENDERED_LANDING_HTML, status_code=200)


# IMPORTANT: mount must be the LAST route declaration so the explicit FastAPI
# routes above take precedence.
app.mount("/", mcp_app)
'''


# ---------------------------------------------------------------------------
# Tool templates (Jinja-rendered)
# ---------------------------------------------------------------------------

GET_TOOL_TEMPLATE = '''
@mcp.tool(
    tags={{ tags }},
    annotations=ToolAnnotations(
        title="{{ title }}",
        readOnlyHint=True,
        destructiveHint=False,
        idempotentHint=True,
        openWorldHint=False,
    ),
)
@subscription_required
async def {{ func_name }}(
    {%- for param in params %}
    {{ param.name }}: {{ param.py_type }}{{ param.default_val }},
    {%- endfor %}
) -> str:
    """{{ description }}"""
    try:
        _require_auth_context()
        query_params: dict[str, Any] = {
            {%- for param in params if param.is_query %}
            "{{ param.original_name }}": {{ param.name }},
            {%- endfor %}
        }
        path_params: dict[str, str] = {}
        {%- for param in params if param.is_path %}
        if {{ param.name }} is not None:
            path_params["{{ param.original_name }}"] = _validate_path_param(
                "{{ param.original_name }}", {{ param.name }}
            )
        {%- endfor %}
        url = "{{ path }}"
        if path_params:
            url = url.format(**path_params)

        response = await _api_client.get(
            url,
            params={k: v for k, v in query_params.items() if v is not None},
        )
        return _format_response(response)
    except ToolInputError as exc:
        return _safe_error("{{ func_name }}", exc)
    except Exception as exc:
        logger.exception("{{ func_name }} failed")
        return _safe_error("{{ func_name }}", exc)
'''


POST_TOOL_TEMPLATE = '''
@mcp.tool(
    tags={{ tags }},
    annotations=ToolAnnotations(
        title="{{ title }}",
        readOnlyHint=False,
        {{ annotations_str }}
    ),
)
@subscription_required
async def {{ func_name }}(
    {%- for param in params %}
    {{ param.name }}: {{ param.py_type }}{{ param.default_val }},
    {%- endfor %}
) -> str:
    """{{ description }}"""
    try:
        _require_auth_context()
        path_params: dict[str, str] = {}
        {%- for param in params if param.is_path %}
        if {{ param.name }} is not None:
            path_params["{{ param.original_name }}"] = _validate_path_param(
                "{{ param.original_name }}", {{ param.name }}
            )
        {%- endfor %}
        body: dict[str, Any] = {
            {%- for param in params if param.is_body %}
            "{{ param.original_name }}": {{ param.name }},
            {%- endfor %}
        }
        {%- if has_webhook_url %}
        if body.get("url") is not None:
            body["url"] = _validate_webhook_url(body["url"])
        {%- endif %}
        url = "{{ path }}"
        if path_params:
            url = url.format(**path_params)

        response = await _api_client.post(
            url,
            json={k: v for k, v in body.items() if v is not None},
        )
        return _format_response(response)
    except ToolInputError as exc:
        return _safe_error("{{ func_name }}", exc)
    except Exception as exc:
        logger.exception("{{ func_name }} failed")
        return _safe_error("{{ func_name }}", exc)
'''


# Hard cap on the upstream Markdown body. ESEF packages can run into the
# hundreds of MB; pulling that into a single Python string blocks the event
# loop and balloons replica memory. The user-facing limit is far below this.
_MAX_FILING_BYTES = 10_000_000


MARKDOWN_TOOL_TEMPLATE = '''
@mcp.tool(
    tags={"Filings"},
    annotations=ToolAnnotations(
        title="{{ title }}",
        readOnlyHint=True,
        destructiveHint=False,
        idempotentHint=True,
        openWorldHint=False,
    ),
)
@subscription_required
async def {{ func_name }}(
    filing_id: int,
    offset: int = 0,
    limit: int = 50000,
) -> str:
    """{{ description }}

    Returns the full processed Markdown content of a filing in pageable chunks.
    For long filings, call this tool repeatedly with increasing `offset` values
    until the response no longer contains the truncation marker. Use a limit
    of 50000 chars (default) for most LLM context windows; the per-call cap
    is 150000 chars (Claude.ai's documented tool-result ceiling).
    """
    try:
        _require_auth_context()
        if not isinstance(filing_id, int) or filing_id <= 0:
            raise ToolInputError("filing_id must be a positive integer")
        if offset < 0:
            raise ToolInputError("offset must be >= 0")
        # Clamp `limit` so a misbehaving caller cannot ask the server to
        # return tens of MB of text in a single call. 150k is the Claude.ai/
        # Claude Desktop documented tool-result ceiling — anything larger
        # gets truncated by the host anyway.
        limit = max(1, min(int(limit), 150000))

        url = f"/filings/{filing_id}/markdown/"

        # Stream so we never buffer more than _MAX_FILING_BYTES into memory,
        # even when the upstream body is much larger than the user's slice.
        async with _api_client.stream("GET", url) as response:
            if response.status_code != 200:
                body = await response.aread()
                return (
                    f"Error {response.status_code} {response.reason_phrase}: "
                    f"{body[:500].decode('utf-8', errors='replace')}"
                )

            buf = bytearray()
            truncated_upstream = False
            async for chunk in response.aiter_bytes():
                if len(buf) + len(chunk) > _MAX_FILING_BYTES:
                    take = _MAX_FILING_BYTES - len(buf)
                    if take > 0:
                        buf.extend(chunk[:take])
                    truncated_upstream = True
                    break
                buf.extend(chunk)

        full_text = buf.decode("utf-8", errors="replace")
        total_length = len(full_text)
        if offset >= total_length:
            return (
                f"--- MARKDOWN CONTENT (chars {offset} to {total_length} of {total_length}) ---\\n"
                "(empty: offset is at or past the end of the document)"
            )
        end_index = min(offset + limit, total_length)
        chunk = full_text[offset:end_index]

        header = (
            f"--- MARKDOWN CONTENT (chars {offset} to {end_index} of {total_length}) ---\\n"
        )
        if end_index < total_length:
            header += (
                f"--- TRUNCATED. Call again with offset={end_index} to continue. ---\\n"
            )
        if truncated_upstream:
            header += (
                f"--- WARNING: filing exceeds {_MAX_FILING_BYTES} bytes; "
                "tail was discarded. ---\\n"
            )

        return header + "\\n" + chunk
    except ToolInputError as exc:
        return _safe_error("filings_markdown_retrieve", exc)
    except Exception as exc:
        logger.exception("filings_markdown_retrieve failed")
        return _safe_error("filings_markdown_retrieve", exc)
'''


# Structured-output GET tools. Same shape as GET_TOOL_TEMPLATE but:
#   - emits `output_schema={...}` on the @mcp.tool decorator, so the
#     server advertises a JSON Schema for its result;
#   - returns the parsed-JSON dict on success so FastMCP can emit
#     `structuredContent` per MCP 2025-11-25 §Tools §Output Schema:
#       "If an output schema is provided: Servers MUST provide structured
#        results that conform to this schema. Clients SHOULD validate."
#   - uses `_authorize_or_raise` instead of `subscription_required` so
#     the unauthorized soft-gate becomes a tool error (markdown payload
#     surfaced via the SubscriptionGateError) — markdown can't be
#     returned alongside a typed schema.
#   - on upstream HTTP errors raises ToolInputError-shaped messages so
#     they surface as `isError: true` text content rather than as a
#     schema-conformance failure.
STRUCTURED_GET_TOOL_TEMPLATE = '''
@mcp.tool(
    tags={{ tags }},
    annotations=ToolAnnotations(
        title="{{ title }}",
        readOnlyHint=True,
        destructiveHint=False,
        idempotentHint=True,
        openWorldHint=False,
    ),
    output_schema={{ output_schema_repr }},
)
async def {{ func_name }}(
    {%- for param in params %}
    {{ param.name }}: {{ param.py_type }}{{ param.default_val }},
    {%- endfor %}
) -> dict[str, Any]:
    """{{ description }}"""
    resets = await _authorize_or_raise()
    try:
        query_params: dict[str, Any] = {
            {%- for param in params if param.is_query %}
            "{{ param.original_name }}": {{ param.name }},
            {%- endfor %}
        }
        path_params: dict[str, str] = {}
        {%- for param in params if param.is_path %}
        if {{ param.name }} is not None:
            path_params["{{ param.original_name }}"] = _validate_path_param(
                "{{ param.original_name }}", {{ param.name }}
            )
        {%- endfor %}
        url = "{{ path }}"
        if path_params:
            url = url.format(**path_params)

        response = await _api_client.get(
            url,
            params={k: v for k, v in query_params.items() if v is not None},
        )
        if response.status_code != 200:
            raise RuntimeError(
                f"upstream {{ func_name }} returned {response.status_code}"
            )
        try:
            return response.json()
        except ValueError as exc:
            raise RuntimeError(f"upstream {{ func_name }} returned non-JSON body") from exc
    finally:
        _release_auth_context(resets)
'''


FILE_FOOTER = '''

# ---------------------------------------------------------------------------
# Local dev entrypoint
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    # Pass the app object directly rather than an import string — the import
    # string form ("module:app") fails when this file is invoked as
    # `python -m src.financial_reports_mcp`, because the actual module path
    # is `src.financial_reports_mcp`, not `financial_reports_mcp`.
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=int(os.environ.get("PORT", "8000")),
        log_level=os.environ.get("LOG_LEVEL", "info").lower(),
    )
'''


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def snake_case(s: str) -> str:
    s = re.sub(r"(?<!^)(?=[A-Z])", "_", s).lower()
    return re.sub(r"[^a-z0-9_]+", "_", s).strip("_")


def resolve_ref(full_schema: dict, ref: str) -> dict:
    if not ref.startswith("#/"):
        return {}
    current: Any = full_schema
    for part in ref[2:].split("/"):
        current = current.get(part, {}) if isinstance(current, dict) else {}
    return current


# Tools whose response shape is well-defined and stable enough to commit
# to as a server-advertised JSON Schema. The MCP 2025-11-25 spec MAKES
# `outputSchema` optional but, when declared, mandates that returned
# results conform — so we keep this list narrow on purpose. Adding new
# tools here is a deliberate spec-contract choice: new tools may be
# added freely with markdown output (no schema) and only get promoted
# to the structured set once their response shape is reviewed.
STRUCTURED_OUTPUT_TOOLS = {
    "companies_list",
    "companies_retrieve",
    "companies_financials_retrieve",
    "filings_list",
    "filings_retrieve",
    "isins_list",
}


def deeply_inline_refs(node: Any, full_schema: dict, _seen: tuple[str, ...] = ()) -> Any:
    """Walk a JSON-Schema fragment and substitute any `$ref` with the
    referenced node, inlined.

    OpenAPI uses `$ref` everywhere; the MCP `outputSchema` field is a
    standalone JSON Schema and renderers can't always follow refs back
    into a parent document. Inlining produces a self-contained schema.

    Cycle protection: `_seen` tracks the chain of refs we're inside; if
    we hit one we've already visited, we stop expansion (replace with
    `{}` so the outer schema is still well-formed). Real OpenAPI rarely
    cycles in response shapes, but defence in depth.
    """
    if isinstance(node, dict):
        if "$ref" in node and isinstance(node["$ref"], str):
            ref = node["$ref"]
            if ref in _seen:
                # Cycle — stop here. The advertised schema becomes a
                # permissive object at this point rather than infinite.
                return {"type": "object", "additionalProperties": True}
            target = resolve_ref(full_schema, ref)
            if not target:
                return {}
            return deeply_inline_refs(target, full_schema, _seen + (ref,))
        out: dict[str, Any] = {}
        for k, v in node.items():
            if k == "$ref":
                continue
            out[k] = deeply_inline_refs(v, full_schema, _seen)
        return out
    if isinstance(node, list):
        return [deeply_inline_refs(item, full_schema, _seen) for item in node]
    return node


def extract_response_schema(operation: dict, full_schema: dict) -> dict | None:
    """Return the `application/json` 200-response JSON Schema for an
    operation, with all `$ref`s deeply inlined. None if the operation
    declares no JSON 200 response."""
    responses = operation.get("responses") or {}
    ok = responses.get("200") or responses.get(200)
    if not isinstance(ok, dict):
        return None
    json_content = (ok.get("content") or {}).get("application/json") or {}
    raw_schema = json_content.get("schema")
    if not raw_schema:
        return None
    return deeply_inline_refs(raw_schema, full_schema)


def get_python_type(schema_type, schema_format=None, is_required=True, default=None):
    py_type = "Any"
    if schema_type == "integer":
        py_type = "int"
    elif schema_type == "number":
        py_type = "float"
    elif schema_type == "string":
        py_type = "str"
    elif schema_type == "boolean":
        py_type = "bool"
    elif schema_type == "array":
        py_type = "list"
    elif schema_type == "object":
        py_type = "dict"

    default_val = ""
    if not is_required:
        py_type = f"{py_type} | None"
        default_val = " = None"

    if default is not None:
        if schema_type == "string":
            default_val = f' = "{default}"'
        else:
            default_val = f" = {default}"

    if is_required and default is None:
        default_val = ""

    return py_type, default_val


def sanitize_description(d: str) -> str:
    """Make an OpenAPI description safe to embed in a Python docstring."""
    if not d:
        return "No description available."
    d = d.strip().replace('"""', "'''")
    if len(d) > 1500:
        d = d[:1500].rstrip() + "..."
    # Collapse runs of whitespace but preserve single newlines for readability
    d = re.sub(r"[ \t]+", " ", d)
    return d


def render_tags(operation: dict) -> str:
    """Render OpenAPI tags as a Python set literal for FastMCP."""
    tags = operation.get("tags", []) or []
    if not tags:
        return "set()"
    quoted = ", ".join(f'"{t}"' for t in tags)
    return "{" + quoted + "}"


def extract_path_params(operation: dict) -> list:
    params = []
    for param in operation.get("parameters", []):
        if param.get("in") != "path":
            continue
        name = param["name"]
        param_schema = param.get("schema", {})
        py_type, default_val = get_python_type(
            param_schema.get("type"),
            param_schema.get("format"),
            param.get("required", True),
            param_schema.get("default"),
        )
        params.append({
            "name": snake_case(name),
            "original_name": name,
            "py_type": py_type,
            "default_val": default_val,
            "is_path": True,
            "is_query": False,
            "is_body": False,
        })
    return params


def extract_body_params(operation: dict, full_schema: dict) -> list:
    params = []
    request_body = operation.get("requestBody", {})
    json_schema = request_body.get("content", {}).get("application/json", {}).get("schema", {})

    if "$ref" in json_schema:
        json_schema = resolve_ref(full_schema, json_schema["$ref"])

    properties = json_schema.get("properties", {})
    required_fields = set(json_schema.get("required", []))

    for prop_name, prop_schema in properties.items():
        if "$ref" in prop_schema:
            prop_schema = resolve_ref(full_schema, prop_schema["$ref"])

        py_type, default_val = get_python_type(
            prop_schema.get("type"),
            prop_schema.get("format"),
            prop_name in required_fields,
            prop_schema.get("default"),
        )
        params.append({
            "name": snake_case(prop_name),
            "original_name": prop_name,
            "py_type": py_type,
            "default_val": default_val,
            "is_path": False,
            "is_query": False,
            "is_body": True,
        })
    return params


def extract_query_params(operation: dict) -> list:
    params = []
    for param in operation.get("parameters", []):
        if param.get("in") != "query":
            continue
        name = param["name"]
        param_schema = param.get("schema", {})
        py_type, default_val = get_python_type(
            param_schema.get("type"),
            param_schema.get("format"),
            param.get("required", False),
            param_schema.get("default"),
        )
        params.append({
            "name": snake_case(name),
            "original_name": name,
            "py_type": py_type,
            "default_val": default_val,
            "is_path": False,
            "is_query": True,
            "is_body": False,
        })
    return params


def compute_post_annotations(func_name: str, path: str) -> str:
    """Compute extra ToolAnnotations kwargs for a POST tool.

    Per Anthropic's connector review guidance, treat all POSTs that mutate
    server state as destructiveHint=True — including creates, since the
    reviewer cares about "can this change my data" not the spec-strict
    "is this delete-shaped". webhooks_test_create is the one exception:
    it's a probe (open world) but doesn't mutate FR state.
    """
    parts: list[str] = []

    if "test_create" in func_name or "test" in func_name.split("_"):
        parts = ["destructiveHint=False", "openWorldHint=True", "idempotentHint=False"]
        return ",\n        ".join(parts)

    if "replay" in func_name:
        parts = ["destructiveHint=False", "openWorldHint=True", "idempotentHint=False"]
        return ",\n        ".join(parts)

    parts = ["destructiveHint=True", "idempotentHint=False", "openWorldHint=False"]
    return ",\n        ".join(parts)


def post_body_has_url_field(operation: dict, full_schema: dict) -> bool:
    """Detect tools that accept a `url` body field.

    Used to wire webhook URL validation into the generated POST wrapper at
    build time without coupling the runtime template to schema knowledge.
    """
    request_body = operation.get("requestBody", {})
    json_schema = (
        request_body.get("content", {}).get("application/json", {}).get("schema", {})
    )
    if "$ref" in json_schema:
        json_schema = resolve_ref(full_schema, json_schema["$ref"])
    return "url" in (json_schema.get("properties") or {})


def render_readme_tool_table(generated_tools: list[dict]) -> str:
    """Build a markdown bullet list of every generated tool, grouped by tag.

    Inserted into README.md between markers so the README cannot drift from
    the live tool surface.
    """
    by_tag: dict[str, list[tuple[str, str]]] = {}
    for tool in generated_tools:
        for tag in tool.get("tags") or ["Other"]:
            by_tag.setdefault(tag, []).append((tool["func_name"], tool["title"]))

    lines: list[str] = []
    for tag in sorted(by_tag):
        lines.append(f"### {tag}")
        for name, title in sorted(by_tag[tag]):
            lines.append(f"* `{name}` — {title}")
        lines.append("")
    return "\n".join(lines).strip() + "\n"


def update_readme_tool_table(repo_root: Path, body: str) -> None:
    readme = repo_root / "README.md"
    if not readme.exists():
        return
    text = readme.read_text(encoding="utf-8")
    start = "<!-- BEGIN AUTO-GENERATED TOOL LIST -->"
    end = "<!-- END AUTO-GENERATED TOOL LIST -->"
    if start not in text or end not in text:
        # Markers not present yet — nothing to do; README will need to be
        # edited once to add them. Avoid mangling user-curated content.
        return
    pre, _, rest = text.partition(start)
    _, _, post = rest.partition(end)
    new = (
        pre
        + start
        + "\n<!-- DO NOT EDIT BY HAND. Re-run scripts/generate_mcp_tools.py. -->\n\n"
        + body
        + "\n"
        + end
        + post
    )
    if new != text:
        readme.write_text(new, encoding="utf-8")
        print(f"📝 Updated tool list in {readme}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    schema = None
    last_exc: Exception | None = None
    for attempt in range(1, 4):
        try:
            print(f"Fetching schema (attempt {attempt}/3)...", file=sys.stderr)
            response = httpx.get(SCHEMA_URL, timeout=120.0)
            response.raise_for_status()
            schema = yaml.safe_load(response.content)
            break
        except Exception as exc:
            last_exc = exc
            print(f"  attempt {attempt} failed: {exc}", file=sys.stderr)
            if attempt < 3:
                time.sleep(5 * attempt)
    if schema is None:
        print(
            f"Failed to download or parse schema after 3 attempts: {last_exc}",
            file=sys.stderr,
        )
        sys.exit(1)

    env = jinja2.Environment(trim_blocks=False, lstrip_blocks=False)
    get_template = env.from_string(GET_TOOL_TEMPLATE)
    structured_get_template = env.from_string(STRUCTURED_GET_TOOL_TEMPLATE)
    post_template = env.from_string(POST_TOOL_TEMPLATE)
    markdown_template = env.from_string(MARKDOWN_TOOL_TEMPLATE)
    structured_count = 0
    missing_response_schema: list[str] = []

    generated_code = [FILE_HEADER_TEMPLATE]
    generated_tools: list[dict] = []

    paths = schema.get("paths", {})
    tool_count = 0
    skipped_no_id = 0
    skipped_methods: list[str] = []

    for path, path_item in paths.items():
        for method, operation in path_item.items():
            if not isinstance(operation, dict):
                continue
            if method.lower() in ("get", "post"):
                continue
            if method.lower() in ("delete", "patch", "put"):
                op_id = operation.get("operationId") or "<unnamed>"
                skipped_methods.append(f"{method.upper()} {path} ({op_id})")

        for method in ("get", "post"):
            if method not in path_item:
                continue

            operation = path_item[method]
            operation_id = operation.get("operationId")
            if not operation_id:
                skipped_no_id += 1
                continue

            func_name = snake_case(operation_id)
            description = sanitize_description(
                operation.get("description") or operation.get("summary") or ""
            )
            tags_value = operation.get("tags", []) or []
            tags = render_tags(operation)
            # Title: prefer the OpenAPI summary (human-written, e.g. "List Companies"),
            # fall back to a Title Case version of the function name. Escape quotes.
            title_raw = (operation.get("summary") or "").strip()
            if not title_raw:
                title_raw = func_name.replace("_", " ").title()
            title = title_raw.replace('"', '\\"')

            if method == "get":
                # Special-case the markdown retrieve endpoint — needs pagination
                if func_name == "filings_markdown_retrieve":
                    generated_code.append(
                        markdown_template.render(
                            func_name=func_name,
                            description=description,
                            title=title,
                        )
                    )
                    tool_count += 1
                    generated_tools.append(
                        {"func_name": func_name, "title": title_raw, "tags": tags_value or ["Filings"]}
                    )
                    continue

                params = extract_path_params(operation) + extract_query_params(operation)
                # Required params first (no default), then optional
                params.sort(key=lambda p: p["default_val"] != "")

                # Promoted to structured output: emit `output_schema=` with
                # the OpenAPI 200-response schema deeply inlined, and use
                # the structured tool template (returns dict, raises on
                # auth failure so FastMCP surfaces it as a tool error
                # instead of trying to fit markdown into the JSON Schema).
                if func_name in STRUCTURED_OUTPUT_TOOLS:
                    response_schema = extract_response_schema(operation, schema)
                    if response_schema is None:
                        missing_response_schema.append(func_name)
                        # Fall through to the unstructured template.
                    else:
                        generated_code.append(
                            structured_get_template.render(
                                func_name=func_name,
                                description=description,
                                params=params,
                                path=path,
                                tags=tags,
                                title=title,
                                output_schema_repr=repr(response_schema),
                            )
                        )
                        tool_count += 1
                        structured_count += 1
                        generated_tools.append(
                            {
                                "func_name": func_name,
                                "title": title_raw,
                                "tags": tags_value,
                            }
                        )
                        continue

                generated_code.append(
                    get_template.render(
                        func_name=func_name,
                        description=description,
                        params=params,
                        path=path,
                        tags=tags,
                        title=title,
                    )
                )
                tool_count += 1
                generated_tools.append(
                    {"func_name": func_name, "title": title_raw, "tags": tags_value}
                )

            elif method == "post":
                path_params = extract_path_params(operation)
                body_params = extract_body_params(operation, schema)
                path_param_names = {p["name"] for p in path_params}
                deduped_body = [p for p in body_params if p["name"] not in path_param_names]
                all_params = path_params + sorted(
                    deduped_body, key=lambda p: p["default_val"] != ""
                )
                annotations_str = compute_post_annotations(func_name, path)
                has_webhook_url = post_body_has_url_field(operation, schema)

                generated_code.append(
                    post_template.render(
                        func_name=func_name,
                        description=description,
                        params=all_params,
                        path=path,
                        tags=tags,
                        annotations_str=annotations_str,
                        title=title,
                        has_webhook_url=has_webhook_url,
                    )
                )
                tool_count += 1
                generated_tools.append(
                    {"func_name": func_name, "title": title_raw, "tags": tags_value}
                )

    generated_code.append(FILE_FOOTER)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(generated_code))

    print(f"✅ Generated {tool_count} tools at {OUTPUT_FILE}")
    if structured_count:
        print(
            f"   ↳ {structured_count} of those advertise an `output_schema` "
            f"(structured-content tools): {sorted(STRUCTURED_OUTPUT_TOOLS)}"
        )
    if missing_response_schema:
        print(
            f"⚠️  STRUCTURED_OUTPUT_TOOLS includes {missing_response_schema} "
            "but the OpenAPI doc has no JSON 200 response schema — fell back "
            "to the unstructured template.",
            file=sys.stderr,
        )
    if skipped_no_id:
        print(f"⚠️  Skipped {skipped_no_id} operations with no operationId")
    if skipped_methods:
        print(
            f"⚠️  Skipped {len(skipped_methods)} non-GET/POST operations "
            "(this generator only emits GET and POST tools):",
            file=sys.stderr,
        )
        for entry in skipped_methods[:20]:
            print(f"     - {entry}", file=sys.stderr)
        if len(skipped_methods) > 20:
            print(f"     ... and {len(skipped_methods) - 20} more", file=sys.stderr)

    update_readme_tool_table(
        OUTPUT_FILE.parent.parent, render_readme_tool_table(generated_tools)
    )


if __name__ == "__main__":
    main()
