"""
generate_mcp_tools.py
=====================

Code generator for the FinancialReports remote MCP server.

What it does:
  1. Pulls the live OpenAPI schema from financialreports.eu
  2. Renders src/financial_reports_mcp.py — a FastAPI host that mounts a
     FastMCP server protected by the FastMCP AWSCognitoProvider OAuth proxy.
  3. Every tool is wrapped in a soft-gate (`@subscription_required`) that
     returns an upgrade-link markdown response for free-tier users instead
     of a hard 403, so the LLM can render the upgrade link inline.

Run:
    python scripts/generate_mcp_tools.py

This script is invoked at Docker build time (see Dockerfile).
"""

import re
import sys
from pathlib import Path

import httpx
import jinja2
import yaml

SCHEMA_URL = "https://financialreports.eu/api/schema/"
OUTPUT_FILE = Path(__file__).parent.parent / "src" / "financial_reports_mcp.py"


# ---------------------------------------------------------------------------
# FILE HEADER — everything above the generated tool functions
# ---------------------------------------------------------------------------
# NOTE: this is a raw Python source string written verbatim to the output file.
# Jinja is NOT applied to it. Only the tool templates below use Jinja.

FILE_HEADER_TEMPLATE = '''"""
AUTO-GENERATED by scripts/generate_mcp_tools.py — DO NOT EDIT MANUALLY.

Architecture:
  - FastAPI host serves /health, /favicon.ico, and a browser landing redirect.
  - FastMCP server (mounted at /mcp) is protected by AWSCognitoProvider, which
    handles the entire OAuth proxy: /authorize, /token, /register,
    /auth/callback, /.well-known/oauth-protected-resource,
    /.well-known/oauth-authorization-server, plus JWKS-based JWT validation.
  - Every tool is decorated with @subscription_required, which checks the
    authenticated user's subscription against the FinancialReports Django
    backend (with a 60s in-memory cache) and returns an upgrade-link
    markdown response for free-tier users.
"""
import os
import logging
from contextlib import asynccontextmanager
from contextvars import ContextVar
from functools import wraps
from typing import Any, Optional

import httpx
import json as _json
import uvicorn
from cachetools import TTLCache
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, RedirectResponse, Response
from fastmcp import FastMCP
from fastmcp.server.auth.providers.aws import AWSCognitoProvider
from fastmcp.server.dependencies import get_access_token
from mcp.types import Icon, ToolAnnotations

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=os.environ.get("LOG_LEVEL", "INFO"),
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("financial-reports-mcp")

# ---------------------------------------------------------------------------
# Configuration (env-driven, no hardcoded secrets)
# ---------------------------------------------------------------------------
COGNITO_USER_POOL_ID = os.environ["COGNITO_USER_POOL_ID"]
COGNITO_CLIENT_ID = os.environ["COGNITO_CLIENT_ID"]
COGNITO_CLIENT_SECRET = os.environ["COGNITO_CLIENT_SECRET"]
COGNITO_REGION = os.environ.get("COGNITO_REGION", "eu-central-1")

MCP_BASE_URL = os.environ.get("MCP_BASE_URL", "https://mcp.financialfilings.com")
API_BASE_URL = os.environ.get("API_BASE_URL", "https://api.financialreports.eu")
VERIFY_URL = os.environ.get(
    "VERIFY_URL",
    "https://api.financialreports.eu/api/mcp/verify/",
)
UPGRADE_URL = os.environ.get(
    "UPGRADE_URL",
    "https://financialreports.eu/pricing/?utm_source=mcp&utm_medium=connector",
)
LANDING_URL = os.environ.get(
    "LANDING_URL",
    "https://financialreports.eu/integrations/mcp/",
)
FAVICON_URL = (
    "https://cdn.financialreports.eu/financialreports/static/"
    "assets/favicon/new/favicon.ico"
)
MCP_VERSION = os.environ.get("MCP_VERSION", "dev")

# ---------------------------------------------------------------------------
# FastMCP server with AWS Cognito OAuth proxy
# ---------------------------------------------------------------------------
auth_provider = AWSCognitoProvider(
    user_pool_id=COGNITO_USER_POOL_ID,
    aws_region=COGNITO_REGION,
    client_id=COGNITO_CLIENT_ID,
    client_secret=COGNITO_CLIENT_SECRET,
    base_url=MCP_BASE_URL,
    redirect_path="/auth/callback",
    required_scopes=["openid", "email", "profile"],
)

mcp = FastMCP(
    name="FinancialReports",
    instructions=(
        "FinancialReports gives you direct access to regulatory filings from "
        "listed companies worldwide — comparable to S&P Capital IQ or FactSet. "
        "Use these tools to search filings, retrieve full filing content as "
        "Markdown, look up companies by name or ISIN, browse industry "
        "classifications, and manage user watchlists. All data is sourced "
        "directly from official regulators."
    ),
    auth=auth_provider,
    icons=[Icon(src=FAVICON_URL, mimeType="image/x-icon")],
)

# ---------------------------------------------------------------------------
# Per-request context (token + user info), set by @subscription_required
# ---------------------------------------------------------------------------
_current_token: ContextVar[str] = ContextVar("_current_token", default="")
_current_user: ContextVar[dict] = ContextVar("_current_user", default={})

# ---------------------------------------------------------------------------
# Subscription verification cache
# ---------------------------------------------------------------------------
# Keyed by Cognito `sub`. 60s TTL absorbs the vast majority of repeated calls
# within a single LLM session while propagating downgrades/cancellations fast.
_subscription_cache: TTLCache = TTLCache(maxsize=10000, ttl=60)


async def _check_subscription(token: str, sub: str) -> dict:
    """Check whether the current user has an active paid subscription.

    Returns a dict with at least an `authorized` bool. Cached per-`sub` for 60s.
    """
    cached = _subscription_cache.get(sub)
    if cached is not None:
        return cached

    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.get(
                VERIFY_URL,
                headers={"Authorization": f"Bearer {token}"},
            )
        if resp.status_code == 200:
            payload = {}
            try:
                payload = resp.json()
            except Exception:
                pass
            result = {
                "authorized": True,
                "plan": payload.get("plan"),
                "user_id": payload.get("user_id"),
                "email": payload.get("email"),
            }
            logger.info("verify ok sub=%s plan=%s", sub[:8], result.get("plan"))
        elif resp.status_code in (401, 403):
            payload = {}
            try:
                payload = resp.json()
            except Exception:
                pass
            result = {
                "authorized": False,
                "reason": payload.get("reason", "subscription_required"),
                "upgrade_url": payload.get("upgrade_url", UPGRADE_URL),
            }
            logger.info(
                "verify denied sub=%s status=%s reason=%s",
                sub[:8],
                resp.status_code,
                result.get("reason"),
            )
        else:
            logger.warning(
                "verify unexpected status=%s body=%s",
                resp.status_code,
                resp.text[:200],
            )
            result = {
                "authorized": False,
                "reason": "verification_failed",
                "upgrade_url": UPGRADE_URL,
            }
    except Exception as exc:
        logger.exception("verify call failed: %s", exc)
        result = {
            "authorized": False,
            "reason": "verification_error",
            "upgrade_url": UPGRADE_URL,
        }

    _subscription_cache[sub] = result
    return result


def _upgrade_response(upgrade_url: str) -> str:
    """Markdown payload returned to free-tier or unauthenticated users.

    The LLM will render the link inline so the end user can click directly
    through to the pricing page from the chat.
    """
    return (
        "⚠️ **Active FinancialReports subscription required**\\n\\n"
        "This tool needs an active **Analyst** or **Enterprise** plan.\\n\\n"
        f"👉 **[Upgrade your account here →]({upgrade_url})**\\n\\n"
        "Once your subscription is active, retry this tool — access is granted "
        "immediately, no reconnection required."
    )


def subscription_required(func):
    """Soft-gate decorator: free users get an upgrade-link markdown response.

    Reads the validated JWT via FastMCP's `get_access_token()`, looks up the
    user's subscription (cached), and either passes through to the wrapped
    function or short-circuits with the upgrade prompt. The wrapped function
    can read the raw token and user info from the contextvars at the top
    of this module.
    """

    @wraps(func)
    async def wrapper(*args, **kwargs):
        try:
            access_token = get_access_token()
        except Exception as exc:
            logger.warning("get_access_token raised: %s", exc)
            return _upgrade_response(UPGRADE_URL)

        if access_token is None:
            return _upgrade_response(UPGRADE_URL)

        claims = getattr(access_token, "claims", {}) or {}
        sub = claims.get("sub")
        raw_token = getattr(access_token, "token", None)

        if not sub or not raw_token:
            logger.warning("missing sub or token on access_token")
            return _upgrade_response(UPGRADE_URL)

        check = await _check_subscription(raw_token, sub)
        if not check.get("authorized"):
            return _upgrade_response(check.get("upgrade_url") or UPGRADE_URL)

        token_reset = _current_token.set(raw_token)
        user_reset = _current_user.set(check)
        try:
            return await func(*args, **kwargs)
        finally:
            _current_token.reset(token_reset)
            _current_user.reset(user_reset)

    return wrapper


# ---------------------------------------------------------------------------
# Backend HTTP client (per-request, scoped to the user's bearer token)
# ---------------------------------------------------------------------------
def _backend_client() -> httpx.AsyncClient:
    """Build an httpx client authenticated as the current MCP user.

    The token is forwarded to api.financialreports.eu, where Django's
    CognitoJWTAuthentication validates it against the same Cognito pool —
    so the user hits API endpoints as themselves and consumes their own quota.
    """
    token = _current_token.get()
    if not token:
        raise RuntimeError("No token in context — tool called outside subscription_required?")
    return httpx.AsyncClient(
        base_url=API_BASE_URL,
        headers={
            "Authorization": f"Bearer {token}",
            "User-Agent": f"FinancialReports-MCP/{MCP_VERSION}",
        },
        timeout=60.0,
    )


async def _format_response(response: httpx.Response) -> str:
    """Format an httpx.Response as a JSON code block for the LLM."""
    try:
        response.raise_for_status()
        data = response.json()
        return f"```json\\n{_json.dumps(data, indent=2, ensure_ascii=False)}\\n```"
    except httpx.HTTPStatusError as exc:
        return (
            f"Error {exc.response.status_code} {exc.response.reason_phrase}: "
            f"{exc.response.text[:500]}"
        )
    except Exception as exc:
        return f"Error formatting response: {exc}"


# ---------------------------------------------------------------------------
# FastAPI host
# ---------------------------------------------------------------------------
# FastMCP returns a Starlette app that already serves /mcp + all OAuth
# endpoints. We mount it at root, with a few FastAPI routes (health, favicon,
# browser landing) declared first so they win the route match.
mcp_app = mcp.http_app(path="/mcp")

app = FastAPI(
    title="FinancialReports MCP Connector",
    version=MCP_VERSION,
    lifespan=mcp_app.lifespan,
    docs_url=None,
    redoc_url=None,
    openapi_url=None,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["mcp-session-id", "mcp-protocol-version"],
)


@app.get("/health")
async def health() -> dict:
    return {
        "status": "ok",
        "service": "financial-reports-mcp",
        "version": MCP_VERSION,
    }


@app.get("/favicon.ico")
async def favicon() -> Response:
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            resp = await client.get(FAVICON_URL)
        return Response(
            content=resp.content,
            media_type="image/x-icon",
            headers={"Cache-Control": "public, max-age=86400"},
        )
    except Exception:
        return Response(status_code=204)


_LANDING_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FinancialReports MCP Server</title>
    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
            color: #e2e8f0;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 24px;
            line-height: 1.6;
        }
        .card {
            background: #1e293b;
            border: 1px solid #334155;
            border-radius: 16px;
            padding: 48px 40px;
            max-width: 640px;
            width: 100%;
            box-shadow: 0 20px 60px rgba(0,0,0,0.4);
        }
        h1 {
            font-size: 28px;
            font-weight: 700;
            margin-bottom: 8px;
            color: #f1f5f9;
            display: flex;
            align-items: center;
            gap: 12px;
        }
        h1 img { width: 36px; height: 36px; }
        .subtitle {
            color: #94a3b8;
            font-size: 16px;
            margin-bottom: 32px;
        }
        .alert {
            background: #422006;
            border: 1px solid #92400e;
            border-radius: 8px;
            padding: 16px 20px;
            margin-bottom: 24px;
            color: #fde68a;
            font-size: 14px;
        }
        .alert strong { color: #fbbf24; }
        .url-block {
            background: #0f172a;
            border: 2px solid #334155;
            border-radius: 10px;
            padding: 20px;
            margin: 24px 0;
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 12px;
        }
        .url-block code {
            font-family: "SF Mono", Menlo, Monaco, "Courier New", monospace;
            font-size: 15px;
            color: #38bdf8;
            font-weight: 600;
            word-break: break-all;
            user-select: all;
        }
        .copy-btn {
            background: #38bdf8;
            color: #0f172a;
            border: none;
            border-radius: 6px;
            padding: 8px 16px;
            font-size: 14px;
            font-weight: 600;
            cursor: pointer;
            white-space: nowrap;
            transition: all 0.15s;
        }
        .copy-btn:hover { background: #7dd3fc; }
        .copy-btn.copied { background: #10b981; color: white; }
        h2 {
            font-size: 18px;
            color: #f1f5f9;
            margin: 32px 0 12px;
            font-weight: 600;
        }
        ol { margin-left: 20px; color: #cbd5e1; font-size: 15px; }
        ol li { margin-bottom: 8px; }
        .footer {
            margin-top: 32px;
            padding-top: 24px;
            border-top: 1px solid #334155;
            color: #64748b;
            font-size: 13px;
            text-align: center;
        }
        .footer a { color: #38bdf8; text-decoration: none; }
        .footer a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <div class="card">
        <h1>
            <img src="/favicon.ico" alt="">
            FinancialReports MCP
        </h1>
        <p class="subtitle">
            Global regulatory filings for AI assistants. You've reached the MCP server endpoint.
        </p>

        <div class="alert">
            <strong>⚠ This URL is incomplete.</strong> To connect your AI assistant, use the full URL with <code>/mcp</code>:
        </div>

        <div class="url-block">
            <code id="mcp-url">https://mcp.financialfilings.com/mcp\</code\>
            <button class="copy-btn" onclick="copyUrl()" id="copy-btn">Copy</button>
        </div>

        <h2>Setup</h2>
        <ol>
            <li>Open your AI assistant's connector / integration settings (Claude, ChatGPT, Cursor, etc.)</li>
            <li>Add a new MCP server with the URL above</li>
            <li>Sign in with your FinancialReports account when prompted</li>
            <li>Start asking about company filings, financials, and disclosures</li>
        </ol>

        <div class="footer">
            Need an account? <a href="https://financialreports.eu/pricing/?utm_source=mcp_landing">View plans</a>
            &nbsp;·&nbsp;
            <a href="https://financialreports.eu/integrations/mcp/">Documentation</a>
        </div>
    </div>

    <script>
        function copyUrl() {
            const url = document.getElementById("mcp-url").textContent;
            const btn = document.getElementById("copy-btn");
            navigator.clipboard.writeText(url).then(() => {
                btn.textContent = "Copied!";
                btn.classList.add("copied");
                setTimeout(() => {
                    btn.textContent = "Copy";
                    btn.classList.remove("copied");
                }, 2000);
            });
        }
    </script>
</body>
</html>"""


@app.get("/", response_class=HTMLResponse)
async def root_landing() -> HTMLResponse:
    """Self-contained landing page for users who hit the bare domain.

    Includes a copy-button for the canonical /mcp URL and step-by-step setup
    instructions. We do NOT redirect or smart-route here — earlier experiments
    with 307-redirects from / to /mcp broke OAuth because Claude/ChatGPT/Cursor
    derive the RFC 8707 resource indicator from the URL the user typed in the
    connector dialog, causing an invalid_target mismatch downstream.
    """
    return HTMLResponse(content=_LANDING_HTML, status_code=200)


# IMPORTANT: mount must be the LAST route declaration so the explicit FastAPI
# routes above take precedence.
app.mount("/", mcp_app)
'''


# ---------------------------------------------------------------------------
# Tool templates (Jinja-rendered)
# ---------------------------------------------------------------------------

GET_TOOL_TEMPLATE = '''
@mcp.tool(tags={{ tags }})
@subscription_required
async def {{ func_name }}(
    {%- for param in params %}
    {{ param.name }}: {{ param.py_type }}{{ param.default_val }},
    {%- endfor %}
) -> str:
    """{{ description }}"""
    try:
        query_params = {
            {%- for param in params if param.is_query %}
            "{{ param.original_name }}": {{ param.name }},
            {%- endfor %}
        }
        path_params = {
            {%- for param in params if param.is_path %}
            "{{ param.original_name }}": {{ param.name }},
            {%- endfor %}
        }
        url = "{{ path }}"
        if path_params:
            url = url.format(**path_params)

        async with _backend_client() as client:
            response = await client.get(
                url,
                params={k: v for k, v in query_params.items() if v is not None},
            )
        return await _format_response(response)
    except Exception as exc:
        logger.exception("{{ func_name }} failed")
        return f"Error calling {{ func_name }}: {exc}"
'''


POST_TOOL_TEMPLATE = '''
@mcp.tool(tags={{ tags }}, annotations=ToolAnnotations({{ annotations_str }}))
@subscription_required
async def {{ func_name }}(
    {%- for param in params %}
    {{ param.name }}: {{ param.py_type }}{{ param.default_val }},
    {%- endfor %}
) -> str:
    """{{ description }}"""
    try:
        path_params = {
            {%- for param in params if param.is_path %}
            "{{ param.original_name }}": {{ param.name }},
            {%- endfor %}
        }
        body = {
            {%- for param in params if param.is_body %}
            "{{ param.original_name }}": {{ param.name }},
            {%- endfor %}
        }
        url = "{{ path }}"
        if path_params:
            url = url.format(**path_params)

        async with _backend_client() as client:
            response = await client.post(
                url,
                json={k: v for k, v in body.items() if v is not None},
            )
        return await _format_response(response)
    except Exception as exc:
        logger.exception("{{ func_name }} failed")
        return f"Error calling {{ func_name }}: {exc}"
'''


MARKDOWN_TOOL_TEMPLATE = '''
@mcp.tool(tags={"Filings"})
@subscription_required
async def {{ func_name }}(
    filing_id: int,
    offset: int = 0,
    limit: int = 50000,
) -> str:
    """{{ description }}

    Returns the full processed Markdown content of a filing in pageable chunks.
    For long filings, call this tool repeatedly with increasing `offset` values
    until the response no longer contains the truncation marker. Use a limit
    of 50000 chars (default) for most LLM context windows.
    """
    try:
        url = f"/filings/{filing_id}/markdown/"
        async with _backend_client() as client:
            response = await client.get(url)

        if response.status_code != 200:
            return (
                f"Error {response.status_code} {response.reason_phrase}: "
                f"{response.text[:500]}"
            )

        full_text = response.text
        total_length = len(full_text)
        end_index = min(offset + limit, total_length)
        chunk = full_text[offset:end_index]

        header = (
            f"--- MARKDOWN CONTENT (chars {offset} to {end_index} of {total_length}) ---\\n"
        )
        if end_index < total_length:
            header += (
                f"--- TRUNCATED. Call again with offset={end_index} to continue. ---\\n"
            )

        return header + "\\n" + chunk
    except Exception as exc:
        logger.exception("filings_markdown_retrieve failed")
        return f"Error retrieving markdown: {exc}"
'''


FILE_FOOTER = '''

# ---------------------------------------------------------------------------
# Local dev entrypoint
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    uvicorn.run(
        "financial_reports_mcp:app",
        host="0.0.0.0",
        port=int(os.environ.get("PORT", "8000")),
        log_level=os.environ.get("LOG_LEVEL", "info").lower(),
    )
'''


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def snake_case(s: str) -> str:
    s = re.sub(r"(?<!^)(?=[A-Z])", "_", s).lower()
    return re.sub(r"[^a-z0-9_]+", "_", s).strip("_")


def resolve_ref(full_schema: dict, ref: str) -> dict:
    if not ref.startswith("#/"):
        return {}
    current: Any = full_schema
    for part in ref[2:].split("/"):
        current = current.get(part, {}) if isinstance(current, dict) else {}
    return current


def get_python_type(schema_type, schema_format=None, is_required=True, default=None):
    py_type = "Any"
    if schema_type == "integer":
        py_type = "int"
    elif schema_type == "number":
        py_type = "float"
    elif schema_type == "string":
        py_type = "str"
    elif schema_type == "boolean":
        py_type = "bool"
    elif schema_type == "array":
        py_type = "list"
    elif schema_type == "object":
        py_type = "dict"

    default_val = ""
    if not is_required:
        py_type = f"{py_type} | None"
        default_val = " = None"

    if default is not None:
        if schema_type == "string":
            default_val = f' = "{default}"'
        else:
            default_val = f" = {default}"

    if is_required and default is None:
        default_val = ""

    return py_type, default_val


def sanitize_description(d: str) -> str:
    """Make an OpenAPI description safe to embed in a Python docstring."""
    if not d:
        return "No description available."
    d = d.strip().replace('"""', "'''")
    if len(d) > 1500:
        d = d[:1500].rstrip() + "..."
    # Collapse runs of whitespace but preserve single newlines for readability
    d = re.sub(r"[ \t]+", " ", d)
    return d


def render_tags(operation: dict) -> str:
    """Render OpenAPI tags as a Python set literal for FastMCP."""
    tags = operation.get("tags", []) or []
    if not tags:
        return "set()"
    quoted = ", ".join(f'"{t}"' for t in tags)
    return "{" + quoted + "}"


def extract_path_params(operation: dict) -> list:
    params = []
    for param in operation.get("parameters", []):
        if param.get("in") != "path":
            continue
        name = param["name"]
        param_schema = param.get("schema", {})
        py_type, default_val = get_python_type(
            param_schema.get("type"),
            param_schema.get("format"),
            param.get("required", True),
            param_schema.get("default"),
        )
        params.append({
            "name": snake_case(name),
            "original_name": name,
            "py_type": py_type,
            "default_val": default_val,
            "is_path": True,
            "is_query": False,
            "is_body": False,
        })
    return params


def extract_body_params(operation: dict, full_schema: dict) -> list:
    params = []
    request_body = operation.get("requestBody", {})
    json_schema = request_body.get("content", {}).get("application/json", {}).get("schema", {})

    if "$ref" in json_schema:
        json_schema = resolve_ref(full_schema, json_schema["$ref"])

    properties = json_schema.get("properties", {})
    required_fields = set(json_schema.get("required", []))

    for prop_name, prop_schema in properties.items():
        if "$ref" in prop_schema:
            prop_schema = resolve_ref(full_schema, prop_schema["$ref"])

        py_type, default_val = get_python_type(
            prop_schema.get("type"),
            prop_schema.get("format"),
            prop_name in required_fields,
            prop_schema.get("default"),
        )
        params.append({
            "name": snake_case(prop_name),
            "original_name": prop_name,
            "py_type": py_type,
            "default_val": default_val,
            "is_path": False,
            "is_query": False,
            "is_body": True,
        })
    return params


def extract_query_params(operation: dict) -> list:
    params = []
    for param in operation.get("parameters", []):
        if param.get("in") != "query":
            continue
        name = param["name"]
        param_schema = param.get("schema", {})
        py_type, default_val = get_python_type(
            param_schema.get("type"),
            param_schema.get("format"),
            param.get("required", False),
            param_schema.get("default"),
        )
        params.append({
            "name": snake_case(name),
            "original_name": name,
            "py_type": py_type,
            "default_val": default_val,
            "is_path": False,
            "is_query": True,
            "is_body": False,
        })
    return params


def compute_post_annotations(func_name: str, path: str) -> str:
    parts = ["readOnlyHint=False"]
    if "bulk_remove" in func_name or "bulk-remove" in path or "destroy" in func_name:
        parts.append("destructiveHint=True")
    if "replay" in func_name or "replay" in path:
        parts.append("openWorldHint=True")
    return ", ".join(parts)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    schema = None
    last_exc = None
    for attempt in range(1, 4):
        try:
            print(f"Fetching schema (attempt {attempt}/3)...", file=sys.stderr)
            response = httpx.get(SCHEMA_URL, timeout=120.0)
            response.raise_for_status()
            schema = yaml.safe_load(response.content)
            break
        except Exception as exc:
            last_exc = exc
            print(f"  attempt {attempt} failed: {exc}", file=sys.stderr)
            if attempt < 3:
                import time
                time.sleep(5 * attempt)
    if schema is None:
        print(f"Failed to download or parse schema after 3 attempts: {last_exc}", file=sys.stderr)
        sys.exit(1)

    env = jinja2.Environment(trim_blocks=False, lstrip_blocks=False)
    get_template = env.from_string(GET_TOOL_TEMPLATE)
    post_template = env.from_string(POST_TOOL_TEMPLATE)
    markdown_template = env.from_string(MARKDOWN_TOOL_TEMPLATE)

    generated_code = [FILE_HEADER_TEMPLATE]

    paths = schema.get("paths", {})
    tool_count = 0
    skipped = 0

    for path, path_item in paths.items():
        for method in ("get", "post"):
            if method not in path_item:
                continue

            operation = path_item[method]
            operation_id = operation.get("operationId")
            if not operation_id:
                skipped += 1
                continue

            func_name = snake_case(operation_id)
            description = sanitize_description(
                operation.get("description") or operation.get("summary") or ""
            )
            tags = render_tags(operation)

            if method == "get":
                # Special-case the markdown retrieve endpoint — needs pagination
                if func_name == "filings_markdown_retrieve":
                    generated_code.append(
                        markdown_template.render(
                            func_name=func_name,
                            description=description,
                        )
                    )
                    tool_count += 1
                    continue

                params = extract_path_params(operation) + extract_query_params(operation)
                # Required params first (no default), then optional
                params.sort(key=lambda p: p["default_val"] != "")

                generated_code.append(
                    get_template.render(
                        func_name=func_name,
                        description=description,
                        params=params,
                        path=path,
                        tags=tags,
                    )
                )
                tool_count += 1

            elif method == "post":
                path_params = extract_path_params(operation)
                body_params = extract_body_params(operation, schema)
                path_param_names = {p["name"] for p in path_params}
                deduped_body = [p for p in body_params if p["name"] not in path_param_names]
                all_params = path_params + sorted(
                    deduped_body, key=lambda p: p["default_val"] != ""
                )
                annotations_str = compute_post_annotations(func_name, path)

                generated_code.append(
                    post_template.render(
                        func_name=func_name,
                        description=description,
                        params=all_params,
                        path=path,
                        tags=tags,
                        annotations_str=annotations_str,
                    )
                )
                tool_count += 1

    generated_code.append(FILE_FOOTER)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(generated_code))

    print(f"✅ Generated {tool_count} tools at {OUTPUT_FILE}")
    if skipped:
        print(f"⚠️  Skipped {skipped} operations with no operationId")


if __name__ == "__main__":
    main()
